OPSIM-1175: update the kinematic model and altazshadowmask basis function
lsst/rubin_scheduler pull request #88
Opened 2024-08-27 01:24 UTC by rhiannonlynne

I expect this PR could have downstream effects on what is scheduled .. depending on how the observatory kinematic model is set up. 
For a fully functioning telescope, with >360 degrees of rotator azimuth range, I don't think it would have that much of an effect. However, it's also true that if we're bumping up against the cumulative azimuth range, this might be an incorrect statement. Depends on the configuration of the AltAzShadowMaskBasisFunction itself during use. 
The kinematic model will now return valid slew times over the parts of the sky which are valid, if provided "no filter" or if given rotSkyPos. This again should have no effect on the actual operations of the kinematic model during baseline sim_runner use, but is useful when trying to diagnose issues later or to just investigate possible slew times.

2024-08-28 00:45 UTC, rhiannonlynne commented
I think what's happening with this failure is that the long gaps survey is requesting an out of bounds scripted survey observation. The scripted survey isn't fully checking against the alt/az limits as it's currently set up in the baseline. 
I wonder if the only reason this wasn't already failing is that we don't usually run very long without having a fully functional observatory. I don't know why the unit test passed previously though .. the alts within the scripted survey aren't picking up the new limits when set up how it is now, so I must need to figure out how to pass them into the scripted survey. I'm inclined to add the AltAzShadowMask function as a default mask for the scripted survey.

2024-08-30 18:42 UTC, rhiannonlynne commented
> I think what's happening with this failure is that the long gaps survey is requesting an out of bounds scripted survey observation. The scripted survey isn't fully checking against the alt/az limits as it's currently set up in the baseline. I wonder if the only reason this wasn't already failing is that we don't usually run very long without having a fully functional observatory. I don't know why the unit test passed previously though .. the alts within the scripted survey aren't picking up the new limits when set up how it is now, so I must need to figure out how to pass them into the scripted survey. I'm inclined to add the AltAzShadowMask function as a default mask for the scripted survey.

This problem was indeed fixed when previous PRs added the AltAzShadowMask to the scripted survey and cleaned up the note handling.

2024-09-03 18:54 UTC, yoachim requested changes
The motivation for refactoring alt/az limits is kind of mysterious. There's not a bug being patched, there's not a performance boost to be had, there's no new functionality being added (and some potentially lost). 

If we want to be able to communicate limited telescope functionality to the scheduler, I would just put that information into the `Conditions` object and have a basis function that is dedicated to interpreting it and generating the correct mask. There's no need to overload the slew time map.

2024-09-03 18:54 UTC, yoachim commented on rubin_scheduler/scheduler/sim_runner.py
> +            mjd_last_flush = observatory.mjd
Might need to be a `mjd_last_flush = copy.copy(observatory.mjd)` because that really needs to not be a pointer.

2024-09-03 18:54 UTC, yoachim commented on rubin_scheduler/scheduler/model_observatory/kinem_model.py
> +        # Delta Azimuth - there are two different 'directions'
Reduce use of "scare quotes" in comments and doc strings. The "directions" have well-understood names of "clockwise" and "anti-clockwise". A scare quote implies you are using a euphemism, and folks reading comments usually want explicit descriptions and not euphemisms.

2024-09-03 19:24 UTC, rhiannonlynne commented on rubin_scheduler/scheduler/model_observatory/model_observatory.py
> +        self.conditions.tel_alt_max = self.observatory.telalt_maxpos_rad
No, [270, 90] will work to remove the north. The order matters for the min/max, which implies the direction of the limits.

2024-09-05 19:29 UTC, rhiannonlynne commented
Summarizing a live conversation about AltAzShadowMask: 
* one goal is that the AltAzShadowMask should be usable to set preferred regions of sky, by the user, as kwargs
* the second is that the AltAzShadowMask should be able to be configurable to know about (possibly dynamic) limitations from the telescope. 

I had tried to get the limitations from the telescope passed as part of the limitations from the telescope configuration - kinematic model, in this case, or observatory model in operations, and figured these were both constraints about physical limitations for the mount (as in, you couldn't even pass through these regions). 
In practice, these may be more complex -- regions you can pass through but don't want to point to (there is a light that is too bright in this direction), vs. "the telescope will hit something" or "the telescope can't focus in this direction"). 
Specifying these different kinds of limits and passing them along lies within the lsst-ts packages, and may not be thoroughly defined yet. (TBD with @tribeiro). 

So we have: 
* kwargs for alt/az regions the user doesn't want to include (these should go back to lists of lists, most likely, so that you can have disjoint regions)
* conditions values for places that should not be pointed at (again, lists of lists, so you can have disjoint regions)
* limitations for the telescope so that we don't slew into places on the sky that are inaccessible.  These should also be passed along to the conditions values above, but may need to be considered separately. (maybe just actually access slew times to mask out places of the sky which are not available?). 

I think this means the kinematic model updates remain the same, the AltAzShadowMaskBasisFunction needs updates, and the way the ModelObservatory passes values to the Conditions (and then the AltAzShadowMaskBasisFunction) needs updates (probably update to something similar to what the previous handling was?).

2024-09-05 19:50 UTC, rhiannonlynne commented on rubin_scheduler/scheduler/model_observatory/model_observatory.py
> +        self.conditions.tel_alt_max = self.observatory.telalt_maxpos_rad
Ok, so I'm kind of thinking that I've managed to conflate a couple of things here. 
Physical limitations on the telescope and telescope model and dynamic limits that may be set due to things unrelated to the mount (bright light in a particular direction). 
In operations, dynamic limits will just have to be sent directly to the Conditions object, and we don't really have a way to mock those at the moment. 
In simulations, it is useful to pick up any changes to the kinematic model automatically, so I'll do that here. 
But in either case, we don't have to run the az_limits / alt_limits lists into and out of the kinematic model, so I'll skip that.

2024-09-07 06:41 UTC, rhiannonlynne commented
After the changes, there are basically discontiguous areas which are (optionally) passed from the observatory model. The AltAzBasisFunction will also pick up limits from the telescope model automatically (which currently isn't a problem in our standard simulations, as we don't degrade the telescope performance .. but might be more of an issue as we evaluate commissioning or early science surveys where the altitude range in particular will be limited).  

The kinematic model is more thoroughly separated from this than previously, in that it doesn't even carry the optional limits now. The slewtime calculation has been updated so that it is possible to calculate slew times with a compromised azimuth range though (previously the kinematic model would return infinite slew times over the whole sky if the available azimuth range was less than 360 degrees). 

There is much more extensive testing of the AltAzShadowMask and some other basis functions.

2024-09-10 17:46 UTC, rhiannonlynne commented
And the same thing (number of observations per scheduler_note) except running on this branch and replacing the ordering in the greedy survey by alt/az again :
<img width="437" alt="Screenshot 2024-09-10 at 10 46 09 AM" src="https://github.com/user-attachments/assets/a7924eb2-02cd-4a66-8ccc-a801134634cb">

2024-09-10 18:22 UTC, rhiannonlynne commented
The problem that this PR addresses is to make it easier to avoid choosing pointings that are in inaccessible regions, without having to set alt/az limits carefully for each survey -- as well as letting them be updated easily via the conditions object using `conditions.kinematic_az_limits` and `conditions.kinematic_alt_limits`, which @tribeiro can pass from the configuration of the observatory model (lsst-ts.ts_observatory_model) into the conditions object in the Driver. Or he could pass them into `conditions.tel_az_limits` and `conditions.tel_alt_limits`  if they are not necessarily appropriate for restriction slew areas but are appropriate for restricting general choices for observing (such as if the AOS system needs to limit the telescope to a given altitude range during commissioning) (presumably these will also be in a yaml file somewhere). 

If a survey is configured with an AltAzShadowMaskBasisFunction, it will then pick up these restrictions automatically and use these to mask parts of the sky which should be inaccessible.

The AltAzShadowMask adds `conditions.altaz_limit_pad` around these constraints, to help avoid choosing pointings which the  healpix reward map states are accessible (such as from the SlewTimeBasisFunction). The mapping from healpix reward map to  pointing can lead to pointings which are ever so slightly outside the reward map - the `altaz_limit_pad` helps avoid this. See screenshot for an example of the reward function without this pad in AltAzShadowMask - healpix map is the slewtime map, the red dots are the pointing centers which the reward function maps to, and the black dot is the chosen pointing ..which is ever so slightly outside the altitude range allowed by the slewtime.  The second screenshot is a *different* simulation and time, but shows how the AltAzShadowMask causes the reward to pull back from the limits for slewtime. 

<img width="975" alt="Screenshot 2024-09-10 at 11 01 31 AM" src="https://github.com/user-attachments/assets/049463fd-4a06-4ee6-b9f0-65a64eee1fa6">
<img width="1001" alt="Screenshot 2024-09-10 at 11 22 03 AM" src="https://github.com/user-attachments/assets/9cb74462-bed1-453a-810d-96a72777cfef">

2024-09-10 18:36 UTC, rhiannonlynne commented
The differences seen in the final unit test which is failing seem to be minor. The difference lies in whether or not the `pairs 33, ri, b` scheduler note is included or not -- with this branch, it is not but in main, it is. There are about 50 observations with this note on main, while here there are none. This is not a negligible number of visits, out of the ~1500 that are acquired over the course of the 3 days included in the unit test. The number of "a" pairs for this blob is also fewer in this branch (19) vs. on main (69) and the overall number of visits is fewer as well (25 less), due to a slightly longer slewtime. 
Interestingly, the scheduler_note `pairs 33, ri, b` can be restored to the output if a previous PR which changed the BlobSurvey ordering from being based on alt/az into ra/dec is reversed. This change was indicated to be not significant previously.

2024-09-10 18:50 UTC, rhiannonlynne commented
For completeness's sake - you can also use the AltAzShadowMaskBasisFunction to restrict the area available on-sky via the arguments for the basis function itself:  
```bfnew = basis_functions.AltAzShadowMaskBasisFunction(min_alt=0, max_alt=90, min_az=270, max_az=90)```
results in available pointings (for the same survey at the same time, but modifying the basis functions): 

<img width="984" alt="Screenshot 2024-09-10 at 11 47 21 AM" src="https://github.com/user-attachments/assets/07ba0297-52dc-4474-93f6-bb467b60b066">

or 
```bfnew = basis_functions.AltAzShadowMaskBasisFunction(min_alt=70, max_alt=90, min_az=0, max_az=360)```

<img width="892" alt="Screenshot 2024-09-10 at 11 49 00 AM" src="https://github.com/user-attachments/assets/85b1e838-9808-4715-9a29-ca6dafc60c07">

or (by reducing the `shadow_minutes`, which adds a mask in areas which are expected to land within the inaccessible region at time = shadow_minutes + current_time) - 
```bfnew = basis_functions.AltAzShadowMaskBasisFunction(min_alt=70, max_alt=90, min_az=0, max_az=360, shadow_minutes=0)```

<img width="848" alt="Screenshot 2024-09-10 at 11 49 50 AM" src="https://github.com/user-attachments/assets/a7ab0419-ad4e-4302-90dc-b1a065e51dba">

2024-09-10 23:44 UTC, yoachim approved these changes
Looks fine on a 5-year run.

2024-09-11 00:15 UTC, merged